### PR TITLE
Made AWS S3 credentials optional

### LINKED ISSUE #102: Can't use IAM role with aws s3, only users with key.
Hi Graham, love this package, good work!

It is missing something - the option to not pass key/secret to the s3 config. This would work when you assign an IAM role to an EC2 instance for bucket permissions instead of using the key/secret of a user. This is the recommended approach when building applications over amazon ec2. 

Right now, inside the AwsS3Connector class, you throw an exception if key or secret are unset, but actually you should simply not add the "credentials" field to the auth object in this case. 

What do you think?

### PR DESCRIPTION
**Pull request by nirradi**
Closes #102.

### CODE REVIEW

File: src/Adapters/AwsS3Connector.php [hunk 1]
```diff
@@ -68,9 +64,15 @@ protected function getAuth(array $config)
         $auth = [
             'region'      => $config['region'],
             'version'     => $config['version'],
-            'credentials' => array_only($config, ['key', 'secret']),
         ];
 
+        if (array_key_exists('key', $config) && $config['key'] != null) {
```
Comment (GrahamCampbell) [inline src/Adapters/AwsS3Connector.php]: I think `isset($config['key'])` is what we want here?

Comment (nirradi) [reply src/Adapters/AwsS3Connector.php]: yeah more succinct.

**Comment by GrahamCampbell** [comment]
Thanks. 👍
